name: Example workflow

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Commit message'
        required: true
  push:
    branches:
      - main
      - dev

jobs:
  example-job:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout codee
        uses: actions/checkout@v2
      - name: Get base branch name
        run: echo "Base branch name is ${{ github.base_ref }}"
      - name: fetch origin 
        run: git fetch origin
      - name: Get head branch name
        run: echo "Head branch name is ${{ github.head_ref }}"\
      - name: Get branch name
        run: git branch -a
      - name: Get current branch name
        run: echo "${GITHUB_REF#refs/heads/}"
      - name: Count modified files
        run: |
           
            ADDED_LINES=$(git diff --shortstat origin/main...origin/dev | awk '{print $4}')
            echo "$ADDED_LINES"
            echo "${{ github.event.head_commit.message }}"
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        
      - name: Analyze code
        run: dart analyze 

      - name: Post comment if errors
        if: ${{ failure() }}
        run: |
            echo " failur "
      - name: Post comment if no errors
        if: ${{ !failure() }}
        run: echo "${{ steps.count_modified_files.outputs.ADDED_LINES }}"


      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#general'
          message: |
            Workflow run completed with status ${{ job.status }}
            Commit message: "${{ github.event.head_commit.message }}"
        if: always()
           
      
