name: Count changed files

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  count-changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get current branch name
        id: branch-name
        run: |
             echo "${GITHUB_REF#refs/heads/}"
             $(git diff origin/main origin/dev --name-only)
             