name: Example workflow

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codee
        uses: actions/checkout@v2
      - name: Get base branch name
        run: echo "Base branch name is ${{ github.base_ref }}"
      - name: fetch origin 
        run: git fetch origin
      - name: Get head branch name
        run: echo "Head branch name is ${{ github.head_ref }}"\
      - name: Get branch name
        run: git branch -a
      - name: Get current branch name
        run: echo "${GITHUB_REF#refs/heads/}"
      - name: Count modified files
        id: file_count
        run: |
          MODIFIED_FILES=$(git diff origin/dev --name-only)
          FILE_COUNT=$(echo "$MODIFIED_FILES" | wc -l)
          echo "$FILE_COUNT"

      - name: Reject PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.file_count.outputs.count > 1
        run: |
          COMMENT_BODY="🚫 This pull request has been automatically rejected because it modifies more than one file. Please create separate pull requests for each file change to ensure better reviewability and maintainability."
          curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\": \"$COMMENT_BODY\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"   

        
