name: Count modified files

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      
      - name: Count modified files
        run: |
               MODIFIED_FILES=$(git diff main --name-only)
               FILE_COUNT=$(echo "$MODIFIED_FILES" | wc -l)
               echo "::set-output name=count::$FILE_COUNT"
