name: Example workflow

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codee
        uses: actions/checkout@v2
      - name: Get base branch name
        run: echo "Base branch name is ${{ github.base_ref }}"
      - name: fetch origin 
        run: git fetch origin
      - name: Get head branch name
        run: echo "Head branch name is ${{ github.head_ref }}"\
      - name: Get branch name
        run: git branch -a
      - name: Get current branch name
        run: echo "${GITHUB_REF#refs/heads/}"
      - name: Count modified files
        id: file_count
        run: |
          MODIFIED_FILES=$(git diff origin/dev --name-only)
          FILE_COUNT=$(echo "$MODIFIED_FILES" | wc -l)
          echo "$FILE_COUNT"

        
