name: Count modified files

on:
  push:
    branches:
          - dev
          - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      
      - name: Count modified files
        run: |
               MODIFIED_FILES=$(git diff main --name-only)
               FILE_COUNT=$(echo "$MODIFIED_FILES" | wc -l)
               echo "::set-output name=count::$FILE_COUNT"

      - name: Refuse Pull Request
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/issues/{issue_number}/comments
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.pull_request.head.repo.name }}
          issue_number: ${{ github.event.pull_request.number }}
          body: |
            ⛔️ This pull request violates the rules. Please check the guidelines and make the necessary changes.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}       
