name: Count modified files

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      
      - name: Count modified files
        run: |
             git log -1
             git diff dev main --name-only

