name: Example workflow

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codee
        uses: actions/checkout@v2
      - name: Get base branch name
        run: echo "Base branch name is ${{ github.base_ref }}"
      - name: fetch origin 
        run: git fetch origin
      - name: Get head branch name
        run: echo "Head branch name is ${{ github.head_ref }}"\
      - name: Get branch name
        run: git branch -a
      - name: Get current branch name
        run: echo "${GITHUB_REF#refs/heads/}"
      - name: Count modified files
        run: |
           
            ADDED_LINES=$(git diff --shortstat origin/main...origin/dev | awk '{print $4}')
            echo "$ADDED_LINES"
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        
      - name: Analyze code
        run: dart analyze 

      - name: Post comment if errors
        if: ${{ failure() }}
        run: |
            echo " failur "
      - name: Post comment if no errors
        if: ${{ !failure() }}
        run: echo "✅ This pull request has passed all checks."
           
      
