name: Example workflow

on:
  pull_request:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get base branch name
        run: echo "Base branch name is ${{ github.base_ref }}"
      - name: Get head branch name
        run: echo "Head branch name is ${{ github.head_ref }}"
      - name: Get current branch name
        run: echo "${GITHUB_REF#refs/heads/}"
      - name: Count modified files
        id: file_count
        run: |
          MODIFIED_FILES=$(git diff dev origin/dev --name-only)
          FILE_COUNT=$(echo "$MODIFIED_FILES" | wc -l)
          echo "$FILE_COUNT"

        
