name: Count modified files

on:
  pull_request:
    types: [opened, synchronize]

    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      
      - name: Count modified files
        run: |
               MODIFIED_FILES=$(git diff main --name-only)
               FILE_COUNT=$(echo "$MODIFIED_FILES" | wc -l)
               echo "$FILE_COUNT"
