name: Example workflow

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codee
        uses: actions/checkout@v2
      - name: Get base branch name
        run: echo "Base branch name is ${{ github.base_ref }}"
      - name: fetch origin 
        run: git fetch origin
      - name: Get head branch name
        run: echo "Head branch name is ${{ github.head_ref }}"\
      - name: Get branch name
        run: git branch -a
      - name: Get current branch name
        run: echo "${GITHUB_REF#refs/heads/}"
      - name: Count modified files
        run: |
            MODIFIED_FILES=$(git diff origin/main origin/dev --name-only)
            FILE_COUNT=$(echo "$MODIFIED_FILES" | wc -l)
            echo "::set-output name=count::$FILE_COUNT"

          # If no conditions are violated, the script will exit successfully.
      
      - name: Refuse Pull Request
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/issues/{issue_number}/comments
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.pull_request.head.repo.name }}
          issue_number: ${{ github.event.pull_request.number }}
          body: |
            ⛔️ This pull request violates the rules. Please check the guidelines and make the necessary changes.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
