name: Example workflow

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codee
        uses: actions/checkout@v2
      - name: Get base branch name
        run: echo "Base branch name is ${{ github.base_ref }}"
      - name: fetch origin 
        run: git fetch origin
      - name: Get head branch name
        run: echo "Head branch name is ${{ github.head_ref }}"\
      - name: Get branch name
        run: git branch -a
      - name: Get current branch name
        run: echo "${GITHUB_REF#refs/heads/}"
      - name: Count modified files
        id: file_count
        run: |
          MODIFIED_FILES=$(git diff origin/main origin/dev --name-only)
          FILE_COUNT=$(echo "$MODIFIED_FILES" | wc -l)
          echo "$FILE_COUNT"
          file_changes_limit=1
          if [ $FILE_COUNT -gt $file_changes_limit ]; then
            echo "::error::This PR exceeds the file changes limit ($file_changes_limit files)."
          fi


      - name: Refuse the pull request
        run: |
          pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          github_token=${{ secrets.GITHUB_TOKEN }}
          curl -X POST \
            -H "Authorization: token $github_token" \
            -H "Content-Type: application/json" \
            -d '{"body": "This pull request does not meet the criteria."}' \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$pr_number/comments"
          echo "::set-output name=refused::true"

      - name: Notify refusal in a PR comment
        if: steps.refuse.outputs.refused == 'true'
        run: echo "This pull request has been refused."

        
